name: ZI Install CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test install
        run: |
          sudo apt update && sudo apt-get install zsh -q
          bash lib/exec/install.sh
